name: CI_CD
on: [push]

jobs:
  CI:
    name: Automated tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Use Node v14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
      - name: Install dependencies
        run: yarn install
      - name: Build all projects
        run: yarn build
      - name: Run automated tests
        run: yarn test
      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
